#!/usr/bin/env python3
"""
BlackHat ToolKit (bhtk) CLI Launcher

Run the toolkit with: bhtk
"""

import sys
import os

# Add bhtk package parent directory to path
# The bhtk package is installed at /usr/local/lib/bhtk/
# So we need to add /usr/local/lib to sys.path
bhtk_lib = '/usr/local/lib'
if bhtk_lib not in sys.path:
    sys.path.insert(0, bhtk_lib)

# Now import and run
from bhtk import __main__
__main__.main()
